version: '3.7'

services:
  loki:
    image: grafana/loki:3.4
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${PWD}/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki  # Единый том для всех данных
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - proznanie_net

  grafana:
    image: grafana/grafana:11.5.1-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - proznanie_net
    depends_on:
      - loki

  fluent-bit:
    image: fluent/fluent-bit:3.2.6
    container_name: fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ${PWD}/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - proznanie_net
    depends_on:
      - loki

volumes:
  grafana-storage:
  loki-data:  # Единый том для всех данных

networks:
  proznanie_net:
    name: proznanie_net
    driver: bridge